version: '3.3'

services:
  raggen-web:
    image: cr.yandex/${REGISTRY_ID}/raggen-web:${VERSION}
    ports:
      - "3000:3000"
    volumes:
      # Монтируем .env файл напрямую в контейнер
      - /opt/raggen/raggen-web/.env:/app/.env
      # Монтируем schema.prisma и директорию для БД
      - ./raggen-web/prisma/schema.prisma:/app/prisma/schema.prisma:ro
      - /opt/raggen/data/sqlite:/app/prisma
    restart: unless-stopped

volumes:
  sqlite-data:
    driver: local
