version: '3.3'

services:
  raggen-embed:
    image: cr.yandex/${REGISTRY_ID}/raggen-embed:${VERSION}
    ports:
      - "8001:8001"
    volumes:
      # Монтируем .env файл напрямую в контейнер
      - /opt/raggen/raggen-embed/.env:/app/.env
      # Монтируем директорию FAISS индексов
      - /opt/raggen/data/faiss:/app/data/faiss
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - LOG_LEVEL=INFO
    restart: unless-stopped

volumes:
  faiss-data:
    driver: local
