version: '3.8'

services:
  raggen-embed:
    image: cr.yandex/${REGISTRY_ID}/raggen-embed:${VERSION}
    build:
      context: ./raggen-embed
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
      tags:
        - cr.yandex/${REGISTRY_ID}/raggen-embed:${VERSION}
        - cr.yandex/${REGISTRY_ID}/raggen-embed:latest
    ports:
      - "8001:8001"
    volumes:
      - ./data/faiss:/app/data/faiss
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - LOG_LEVEL=INFO
    restart: unless-stopped

  raggen-web:
    image: cr.yandex/${REGISTRY_ID}/raggen-web:${VERSION}
    build:
      context: ./raggen-web
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
      tags:
        - cr.yandex/${REGISTRY_ID}/raggen-web:${VERSION}
        - cr.yandex/${REGISTRY_ID}/raggen-web:latest
    ports:
      - "3000:3000"
    volumes:
      - ./raggen-web/prisma/dev.db:/app/prisma/dev.db
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
      - NEXT_PUBLIC_EMBED_API_URL=http://raggen-embed:8001
    depends_on:
      - raggen-embed
    restart: unless-stopped

volumes:
  faiss-data:
    driver: local
  sqlite-data:
    driver: local 